application: mapromanager
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /img/(.*\.(gif|png|jpg))
  static_files: static/img/\1
  upload: static/img/(.*\.(gif|png|jpg))
  
- url: /apple-touch-icon\.png
  mime_type: image/png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon.png

- url: /favicon\.ico
  mime_type: image/png
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(robots\.txt|humans\.txt|crossdomain\.xml)
  static_files: static/\1
  upload: static/(robots\.txt|humans\.txt|crossdomain\.xml)

- url: /(.*\.(appcache|manifest))
  mime_type: text/cache-manifest
  static_files: static/\1
  upload: static/(.*\.(appcache|manifest))
  expiration: "0m"

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.ico)
  mime_type: image/x-icon
  static_files: static/\1
  upload: static/(.*\.ico)
  expiration: "7d"

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  
- url: /css
  mime_type: text/css
  static_dir: static/css
  
- url: /.*
  script: dojo.applic
  login: required
  
- url: /_ah/login_required
  script: do_openid_login.app
  
  
libraries:
- name: jinja2
  version: "2.6"